from __future__ import annotations

import unittest

from services.output_manifest import csv_with_manifest_comment, manifest_comment, svg_with_metadata


class OutputManifestTests(unittest.TestCase):
    def test_csv_manifest_comment_is_prepended(self) -> None:
        payload = csv_with_manifest_comment("x,y\n1,2\n", "abc123", version="bte v0.6.0")

        self.assertTrue(
            payload.decode("utf-8").startswith("# generated by bte v0.6.0 from manifest abc123")
        )

    def test_default_manifest_comment_records_runtime_provenance(self) -> None:
        text = manifest_comment("abc123")

        self.assertIn("bioelectronics_toolkit v", text)
        self.assertIn("dependencies numpy=", text)
        self.assertIn("scipy=", text)
        self.assertIn("pandas=", text)
        self.assertIn("tifffile=", text)
        self.assertNotIn("generated by bioelectronics_toolkit from manifest", text)

    def test_svg_metadata_is_inserted_under_root(self) -> None:
        payload = svg_with_metadata("<svg><path /></svg>", {"manifest": "abc123"})
        text = payload.decode("utf-8")

        self.assertIn("<svg>\n<metadata>", text)
        self.assertIn("&quot;manifest&quot;: &quot;abc123&quot;", text)
        self.assertIn("&quot;provenance&quot;", text)
        self.assertIn("&quot;dependencies&quot;", text)


if __name__ == "__main__":
    unittest.main()
