from __future__ import annotations

from services.histology_batch_core import (
    TREATMENT_SORT_ORDER,
    _aggregate_roi_rows_by_entry,
    _apply_batch_grouping,
    _apply_marker_inclusion,
    _apply_normalization_to_rows,
    _batch_anova,
    _batch_group_summary,
    _batch_timestamp_slug,
    _boolish,
    _canonical_treatment_label,
    _extract_sample_group,
    _extract_source_letter,
    _finite_float,
    _flatten_batch_row,
    _group_sort_key,
    _mean_sd_sem,
    _metric_column,
    _new_project_batch_dir,
    _normalize_batch_rows,
    _normalized_metric_column,
    _numeric_mean,
    _params_for_roi_parameter_override,
    _parse_image_sample_and_treatment,
    _roi_parameter_override_candidates,
    _roi_parameter_overrides,
    _row_metric_value,
    _scalar_for_table,
)
from services.histology_batch_outputs import (
    _anova_label,
    _finite_float_list,
    _plot_color,
    _save_batch_plot,
    _write_batch_outputs,
    _write_csv_records,
)
from services.histology_analysis import ANALYSIS_VERSION, _now_iso, _write_json
from services.histology_data_project_paths import _data_project_dir
from services.matplotlib_utils import close_figure, new_subplots

__all__ = [
    "ANALYSIS_VERSION",
    "TREATMENT_SORT_ORDER",
    "_aggregate_roi_rows_by_entry",
    "_anova_label",
    "_apply_batch_grouping",
    "_apply_marker_inclusion",
    "_apply_normalization_to_rows",
    "_batch_anova",
    "_batch_group_summary",
    "_batch_timestamp_slug",
    "_boolish",
    "_canonical_treatment_label",
    "_data_project_dir",
    "_extract_sample_group",
    "_extract_source_letter",
    "_finite_float",
    "_finite_float_list",
    "_flatten_batch_row",
    "_group_sort_key",
    "_mean_sd_sem",
    "_metric_column",
    "_new_project_batch_dir",
    "_now_iso",
    "_normalize_batch_rows",
    "_normalized_metric_column",
    "_numeric_mean",
    "_params_for_roi_parameter_override",
    "_parse_image_sample_and_treatment",
    "_plot_color",
    "_roi_parameter_override_candidates",
    "_roi_parameter_overrides",
    "_row_metric_value",
    "_save_batch_plot",
    "_scalar_for_table",
    "_write_batch_outputs",
    "_write_csv_records",
    "_write_json",
    "close_figure",
    "new_subplots",
]
