from __future__ import annotations

import json
from html import escape
from typing import Any


def manifest_comment(manifest_ref: str, *, version: str = "bioelectronics_toolkit") -> str:
    ref = str(manifest_ref or "").strip()
    return f"# generated by {version} from manifest {ref}".rstrip()


def csv_with_manifest_comment(
    payload: str | bytes,
    manifest_ref: str,
    *,
    version: str = "bioelectronics_toolkit",
) -> bytes:
    body = payload.decode("utf-8") if isinstance(payload, bytes) else str(payload)
    return f"{manifest_comment(manifest_ref, version=version)}\n{body}".encode("utf-8")


def svg_metadata_element(metadata: dict[str, Any]) -> str:
    payload = json.dumps(metadata, ensure_ascii=False, sort_keys=True)
    return f"<metadata>{escape(payload)}</metadata>"


def svg_with_metadata(svg_payload: str | bytes, metadata: dict[str, Any]) -> bytes:
    text = svg_payload.decode("utf-8") if isinstance(svg_payload, bytes) else str(svg_payload)
    element = svg_metadata_element(metadata)
    insert_at = text.find(">")
    if insert_at < 0 or "<svg" not in text[: max(5, insert_at + 1)].lower():
        return f"{element}\n{text}".encode("utf-8")
    return f"{text[: insert_at + 1]}\n{element}{text[insert_at + 1:]}".encode("utf-8")
