from __future__ import annotations

import json
from html import escape
from typing import Any

from services.provenance import dependency_label, generator_label, runtime_provenance


def manifest_comment(
    manifest_ref: str,
    *,
    version: str | None = None,
    provenance: dict[str, Any] | None = None,
) -> str:
    ref = str(manifest_ref or "").strip()
    label = version or generator_label(provenance)
    deps = "" if version else f"; dependencies {dependency_label(provenance=provenance)}"
    return f"# generated by {label}{deps} from manifest {ref}".rstrip()


def csv_with_manifest_comment(
    payload: str | bytes,
    manifest_ref: str,
    *,
    version: str | None = None,
    provenance: dict[str, Any] | None = None,
) -> bytes:
    body = payload.decode("utf-8") if isinstance(payload, bytes) else str(payload)
    return f"{manifest_comment(manifest_ref, version=version, provenance=provenance)}\n{body}".encode(
        "utf-8"
    )


def metadata_with_provenance(
    metadata: dict[str, Any],
    *,
    provenance: dict[str, Any] | None = None,
) -> dict[str, Any]:
    out = dict(metadata or {})
    out.setdefault("provenance", provenance or runtime_provenance())
    return out


def svg_metadata_element(
    metadata: dict[str, Any],
    *,
    provenance: dict[str, Any] | None = None,
) -> str:
    payload = json.dumps(
        metadata_with_provenance(metadata, provenance=provenance),
        ensure_ascii=False,
        sort_keys=True,
    )
    return f"<metadata>{escape(payload)}</metadata>"


def svg_with_metadata(
    svg_payload: str | bytes,
    metadata: dict[str, Any],
    *,
    provenance: dict[str, Any] | None = None,
) -> bytes:
    text = svg_payload.decode("utf-8") if isinstance(svg_payload, bytes) else str(svg_payload)
    element = svg_metadata_element(metadata, provenance=provenance)
    insert_at = text.find(">")
    if insert_at < 0 or "<svg" not in text[: max(5, insert_at + 1)].lower():
        return f"{element}\n{text}".encode("utf-8")
    return f"{text[: insert_at + 1]}\n{element}{text[insert_at + 1 :]}".encode("utf-8")
